# -*- coding: utf-8 -*-
"""evaluate_on _unseen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

import os
import random
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO


MODEL_PATH = "/content/runs/detect/train/weights/best.pt"


TEST_IMAGES_DIR = "/content/dataset_E/images"


OUTPUT_RESULTS_DIR = "dataset_E_predictions"


model = YOLO(MODEL_PATH)

print(f"Running inference on unseen images in: {TEST_IMAGES_DIR}")


results = model.predict(
    source=TEST_IMAGES_DIR,
    conf=0.25,           # Confidence threshold
    iou=0.45,            # NMS IoU threshold
    save=True,           # Save annotated images to disk
    project=OUTPUT_RESULTS_DIR,
    name="visual_results",
    exist_ok=True
)

print(f"\nInference complete! Visual predictions saved directly to: {OUTPUT_RESULTS_DIR}/visual_results")

import os
from ultralytics import YOLO


MODEL_PATH = "/content/runs/detect/train/weights/best.pt"
DATASET_DIR = "/content/dataset_E"
YAML_PATH = "dataset_E.yaml"



yaml_content = f"""
path: {os.path.abspath(DATASET_DIR)}
train: images
val: images

names:
  0: flag
"""

with open(YAML_PATH, "w") as f:
    f.write(yaml_content.strip())

print(f"Created updated config file: {YAML_PATH}")


model = YOLO(MODEL_PATH)

print(f"Evaluating model on unseen data...")
metrics = model.val(
    data=YAML_PATH,
    split="val",
    plots=True
)


precision = metrics.box.mp       # Mean Precision
recall = metrics.box.mr          # Mean Recall
map50 = metrics.box.map50        # mAP at threshold 0.50
map95 = metrics.box.map          # mAP at thresholds 0.50-0.95


print("\n" + "="*40)
print("       UNSEEN DATASET TEST METRICS      ")
print("="*40)
print(f"Precision (P):   {precision * 100:.2f}%")
print(f"Recall (R):      {recall * 100:.2f}%")
print(f"mAP50:           {map50:.4f}")
print(f"mAP50-95:        {map95:.4f}")
print("="*40)
print(f"Curves and confusion matrices saved to: {metrics.save_dir}")

