# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

model = YOLO("/content/runs/detect/train/weights/best.pt")

metrics = model.val(
    data="/content/data.yaml",
    split="test"
)

print("\n===== TEST RESULTS =====")

print("mAP50:",
      metrics.box.map50)

print("mAP50-95:",
      metrics.box.map)

print("Precision:",
      metrics.box.mp)

print("Recall:",
      metrics.box.mr)

import glob
import time

test_images = glob.glob(
    "/content/dataset_D/images/test/*.jpg"
)

start = time.time()

for img in test_images:
    model.predict(
        img,
        verbose=False
    )

total_time = time.time() - start

fps = len(test_images) / total_time

print("\n===== INFERENCE =====")

print(
    f"Total Time: {total_time:.2f} sec"
)

print(
    f"Images/sec: {fps:.2f}"
)

print(
    f"Milliseconds/image: {1000/fps:.2f}"
)