# -*- coding: utf-8 -*-
"""train yolov8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile data.yaml
# 
# path: /content/dataset
# 
# train: images/train
# val: images/val
# test: images/test
# 
# names:
#   0: flag

import time
from ultralytics import YOLO

start_time = time.time()

model = YOLO("yolov8n.pt")

results = model.train(
    data="/content/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    device=0
)

training_time = time.time() - start_time

print(f"\nTraining Time: {training_time:.2f} seconds")
print(f"Training Time: {training_time/60:.2f} minutes")