# -*- coding: utf-8 -*-
"""train faster_rcnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AJep9HyFj-wJsNjGvUTZAXiSxQ0z2XR
"""

from torch.utils.data import Dataset
import cv2
import torch
import os

class FlagDataset(Dataset):

    def __init__(self, image_dir, label_dir):
        self.image_dir = image_dir
        self.label_dir = label_dir

        self.images = sorted(os.listdir(image_dir))

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):

        image_name = self.images[idx]

        image_path = os.path.join(self.image_dir, image_name)

        image = cv2.imread(image_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        h, w = image.shape[:2]

        label_path = os.path.join(
            self.label_dir,
            image_name.replace(".jpg", ".txt")
        )

        boxes = []

        with open(label_path) as f:
            lines = f.readlines()

            for line in lines:

                cls, xc, yc, bw, bh = map(float, line.split())

                xmin = (xc - bw/2) * w
                ymin = (yc - bh/2) * h
                xmax = (xc + bw/2) * w
                ymax = (yc + bh/2) * h

                boxes.append([xmin, ymin, xmax, ymax])

        boxes = torch.tensor(boxes, dtype=torch.float32)

        labels = torch.ones((len(boxes),), dtype=torch.int64)

        target = {
            "boxes": boxes,
            "labels": labels
        }

        image = torch.tensor(image).permute(2,0,1).float()/255.0

        return image, target

from torch.utils.data import DataLoader

def collate_fn(batch):
    return tuple(zip(*batch))

train_dataset= FlagDataset(
    image_dir="/content/dataset/images/train",
    label_dir="/content/dataset/labels/train"
)
train_loader = DataLoader(
    train_dataset,
    batch_size=4,
    shuffle=True,
    collate_fn=collate_fn
)
val_dataset = FlagDataset(
    image_dir="/content/dataset/images/val",
    label_dir="/content/dataset/labels/val"
)
val_loader = DataLoader(
    val_dataset,
    batch_size=4,
    shuffle=False,
    collate_fn=collate_fn
)

import torchvision

from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

num_classes = 2
# background + flag

in_features = model.roi_heads.box_predictor.cls_score.in_features

model.roi_heads.box_predictor = FastRCNNPredictor(
    in_features,
    num_classes
)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model.to(device)

import torch.optim as optim
optimizer = optim.SGD(
    model.parameters(),
    lr=0.005,
    momentum=0.9,
    weight_decay=0.0005
)

num_epochs = 10

for epoch in range(num_epochs):


    # TRAINING

    model.train()
    train_loss = 0.0

    for images, targets in train_loader:
        images = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        loss_dict = model(images, targets)
        losses = sum(loss for loss in loss_dict.values())

        optimizer.zero_grad()
        losses.backward()
        optimizer.step()

        train_loss += losses.item()

    avg_train_loss = train_loss / len(train_loader)


    # VALIDATION LOSS

    model.train()
    val_loss = 0.0


    with torch.no_grad():
        for images, targets in val_loader:
            images = [img.to(device) for img in images]
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            loss_dict = model(images, targets)
            losses = sum(loss for loss in loss_dict.values())


            val_loss += losses.item()


            optimizer.zero_grad(set_to_none=True)

    avg_val_loss = val_loss / len(val_loader)

    print(
        f"Epoch {epoch+1}/{num_epochs} | "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Val Loss: {avg_val_loss:.4f}"
    )

num_epochs = 20

for epoch in range(num_epochs):


    # TRAINING

    model.train()
    train_loss = 0.0

    for images, targets in train_loader:
        images = [img.to(device) for img in images]
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        loss_dict = model(images, targets)
        losses = sum(loss for loss in loss_dict.values())

        optimizer.zero_grad()
        losses.backward()
        optimizer.step()

        train_loss += losses.item()

    avg_train_loss = train_loss / len(train_loader)


    # VALIDATION LOSS

    model.train()
    val_loss = 0.0


    with torch.no_grad():
        for images, targets in val_loader:
            images = [img.to(device) for img in images]
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            loss_dict = model(images, targets)
            losses = sum(loss for loss in loss_dict.values())


            val_loss += losses.item()


            optimizer.zero_grad(set_to_none=True)

    avg_val_loss = val_loss / len(val_loader)

    print(
        f"Epoch {epoch+1}/{num_epochs} | "
        f"Train Loss: {avg_train_loss:.4f} | "
        f"Val Loss: {avg_val_loss:.4f}"
    )